// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage/v1/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

type UploadObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadObjectRequest) Reset() {
	*x = UploadObjectRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectRequest) ProtoMessage() {}

func (x *UploadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectRequest.ProtoReflect.Descriptor instead.
func (*UploadObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadObjectRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UploadObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadObjectResponse) Reset() {
	*x = UploadObjectResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectResponse) ProtoMessage() {}

func (x *UploadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadObjectResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

type GetObjectMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectMetadataRequest) Reset() {
	*x = GetObjectMetadataRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectMetadataRequest) ProtoMessage() {}

func (x *GetObjectMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetObjectMetadataRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectMetadataRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetObjectMetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetObjectMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectMetadataResponse) Reset() {
	*x = GetObjectMetadataResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectMetadataResponse) ProtoMessage() {}

func (x *GetObjectMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetObjectMetadataResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectMetadataResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetObjectMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetObjectMetadataResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetObjectMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ListObjectsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListObjectsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectNames   []string               `protobuf:"bytes,1,rep,name=object_names,json=objectNames,proto3" json:"object_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ListObjectsResponse) GetObjectNames() []string {
	if x != nil {
		return x.ObjectNames
	}
	return nil
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *GetDownloadURLRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetDownloadURLRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *GetDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\n" +
	"storage.v1\")\n" +
	"\x13CreateBucketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14CreateBucketResponse\"\xdd\x01\n" +
	"\x13UploadObjectRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.storage.v1.UploadObjectRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14UploadObjectResponse\"F\n" +
	"\x18GetObjectMetadataRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe9\x01\n" +
	"\x19GetObjectMetadataResponse\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12O\n" +
	"\bmetadata\x18\x04 \x03(\v23.storage.v1.GetObjectMetadataResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x12ListObjectsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"8\n" +
	"\x13ListObjectsResponse\x12!\n" +
	"\fobject_names\x18\x01 \x03(\tR\vobjectNames\"C\n" +
	"\x15GetDownloadURLRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x16GetDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xc1\x03\n" +
	"\x0eStorageService\x12Q\n" +
	"\fCreateBucket\x12\x1f.storage.v1.CreateBucketRequest\x1a .storage.v1.CreateBucketResponse\x12Q\n" +
	"\fUploadObject\x12\x1f.storage.v1.UploadObjectRequest\x1a .storage.v1.UploadObjectResponse\x12`\n" +
	"\x11GetObjectMetadata\x12$.storage.v1.GetObjectMetadataRequest\x1a%.storage.v1.GetObjectMetadataResponse\x12N\n" +
	"\vListObjects\x12\x1e.storage.v1.ListObjectsRequest\x1a\x1f.storage.v1.ListObjectsResponse\x12W\n" +
	"\x0eGetDownloadURL\x12!.storage.v1.GetDownloadURLRequest\x1a\".storage.v1.GetDownloadURLResponseBhZfOlympusGCP-Storage/gen/v1/storage;storagev1b\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_storage_v1_storage_proto_goTypes = []any{
	(*CreateBucketRequest)(nil),       // 0: storage.v1.CreateBucketRequest
	(*CreateBucketResponse)(nil),      // 1: storage.v1.CreateBucketResponse
	(*UploadObjectRequest)(nil),       // 2: storage.v1.UploadObjectRequest
	(*UploadObjectResponse)(nil),      // 3: storage.v1.UploadObjectResponse
	(*GetObjectMetadataRequest)(nil),  // 4: storage.v1.GetObjectMetadataRequest
	(*GetObjectMetadataResponse)(nil), // 5: storage.v1.GetObjectMetadataResponse
	(*ListObjectsRequest)(nil),        // 6: storage.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),       // 7: storage.v1.ListObjectsResponse
	(*GetDownloadURLRequest)(nil),     // 8: storage.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),    // 9: storage.v1.GetDownloadURLResponse
	nil,                               // 10: storage.v1.UploadObjectRequest.MetadataEntry
	nil,                               // 11: storage.v1.GetObjectMetadataResponse.MetadataEntry
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	10, // 0: storage.v1.UploadObjectRequest.metadata:type_name -> storage.v1.UploadObjectRequest.MetadataEntry
	11, // 1: storage.v1.GetObjectMetadataResponse.metadata:type_name -> storage.v1.GetObjectMetadataResponse.MetadataEntry
	0,  // 2: storage.v1.StorageService.CreateBucket:input_type -> storage.v1.CreateBucketRequest
	2,  // 3: storage.v1.StorageService.UploadObject:input_type -> storage.v1.UploadObjectRequest
	4,  // 4: storage.v1.StorageService.GetObjectMetadata:input_type -> storage.v1.GetObjectMetadataRequest
	6,  // 5: storage.v1.StorageService.ListObjects:input_type -> storage.v1.ListObjectsRequest
	8,  // 6: storage.v1.StorageService.GetDownloadURL:input_type -> storage.v1.GetDownloadURLRequest
	1,  // 7: storage.v1.StorageService.CreateBucket:output_type -> storage.v1.CreateBucketResponse
	3,  // 8: storage.v1.StorageService.UploadObject:output_type -> storage.v1.UploadObjectResponse
	5,  // 9: storage.v1.StorageService.GetObjectMetadata:output_type -> storage.v1.GetObjectMetadataResponse
	7,  // 10: storage.v1.StorageService.ListObjects:output_type -> storage.v1.ListObjectsResponse
	9,  // 11: storage.v1.StorageService.GetDownloadURL:output_type -> storage.v1.GetDownloadURLResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
