// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: storage/v1/storage.proto

package storagev1connect

import (
	v1 "OlympusGCP-Storage/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/storage/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StorageServiceName is the fully-qualified name of the StorageService service.
	StorageServiceName = "storage.v1.StorageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StorageServiceCreateBucketProcedure is the fully-qualified name of the StorageService's
	// CreateBucket RPC.
	StorageServiceCreateBucketProcedure = "/storage.v1.StorageService/CreateBucket"
	// StorageServiceUploadObjectProcedure is the fully-qualified name of the StorageService's
	// UploadObject RPC.
	StorageServiceUploadObjectProcedure = "/storage.v1.StorageService/UploadObject"
	// StorageServiceGetObjectMetadataProcedure is the fully-qualified name of the StorageService's
	// GetObjectMetadata RPC.
	StorageServiceGetObjectMetadataProcedure = "/storage.v1.StorageService/GetObjectMetadata"
	// StorageServiceListObjectsProcedure is the fully-qualified name of the StorageService's
	// ListObjects RPC.
	StorageServiceListObjectsProcedure = "/storage.v1.StorageService/ListObjects"
	// StorageServiceGetDownloadURLProcedure is the fully-qualified name of the StorageService's
	// GetDownloadURL RPC.
	StorageServiceGetDownloadURLProcedure = "/storage.v1.StorageService/GetDownloadURL"
)

// StorageServiceClient is a client for the storage.v1.StorageService service.
type StorageServiceClient interface {
	CreateBucket(context.Context, *connect.Request[v1.CreateBucketRequest]) (*connect.Response[v1.CreateBucketResponse], error)
	UploadObject(context.Context, *connect.Request[v1.UploadObjectRequest]) (*connect.Response[v1.UploadObjectResponse], error)
	GetObjectMetadata(context.Context, *connect.Request[v1.GetObjectMetadataRequest]) (*connect.Response[v1.GetObjectMetadataResponse], error)
	ListObjects(context.Context, *connect.Request[v1.ListObjectsRequest]) (*connect.Response[v1.ListObjectsResponse], error)
	GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error)
}

// NewStorageServiceClient constructs a client for the storage.v1.StorageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStorageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StorageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	storageServiceMethods := v1.File_storage_v1_storage_proto.Services().ByName("StorageService").Methods()
	return &storageServiceClient{
		createBucket: connect.NewClient[v1.CreateBucketRequest, v1.CreateBucketResponse](
			httpClient,
			baseURL+StorageServiceCreateBucketProcedure,
			connect.WithSchema(storageServiceMethods.ByName("CreateBucket")),
			connect.WithClientOptions(opts...),
		),
		uploadObject: connect.NewClient[v1.UploadObjectRequest, v1.UploadObjectResponse](
			httpClient,
			baseURL+StorageServiceUploadObjectProcedure,
			connect.WithSchema(storageServiceMethods.ByName("UploadObject")),
			connect.WithClientOptions(opts...),
		),
		getObjectMetadata: connect.NewClient[v1.GetObjectMetadataRequest, v1.GetObjectMetadataResponse](
			httpClient,
			baseURL+StorageServiceGetObjectMetadataProcedure,
			connect.WithSchema(storageServiceMethods.ByName("GetObjectMetadata")),
			connect.WithClientOptions(opts...),
		),
		listObjects: connect.NewClient[v1.ListObjectsRequest, v1.ListObjectsResponse](
			httpClient,
			baseURL+StorageServiceListObjectsProcedure,
			connect.WithSchema(storageServiceMethods.ByName("ListObjects")),
			connect.WithClientOptions(opts...),
		),
		getDownloadURL: connect.NewClient[v1.GetDownloadURLRequest, v1.GetDownloadURLResponse](
			httpClient,
			baseURL+StorageServiceGetDownloadURLProcedure,
			connect.WithSchema(storageServiceMethods.ByName("GetDownloadURL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// storageServiceClient implements StorageServiceClient.
type storageServiceClient struct {
	createBucket      *connect.Client[v1.CreateBucketRequest, v1.CreateBucketResponse]
	uploadObject      *connect.Client[v1.UploadObjectRequest, v1.UploadObjectResponse]
	getObjectMetadata *connect.Client[v1.GetObjectMetadataRequest, v1.GetObjectMetadataResponse]
	listObjects       *connect.Client[v1.ListObjectsRequest, v1.ListObjectsResponse]
	getDownloadURL    *connect.Client[v1.GetDownloadURLRequest, v1.GetDownloadURLResponse]
}

// CreateBucket calls storage.v1.StorageService.CreateBucket.
func (c *storageServiceClient) CreateBucket(ctx context.Context, req *connect.Request[v1.CreateBucketRequest]) (*connect.Response[v1.CreateBucketResponse], error) {
	return c.createBucket.CallUnary(ctx, req)
}

// UploadObject calls storage.v1.StorageService.UploadObject.
func (c *storageServiceClient) UploadObject(ctx context.Context, req *connect.Request[v1.UploadObjectRequest]) (*connect.Response[v1.UploadObjectResponse], error) {
	return c.uploadObject.CallUnary(ctx, req)
}

// GetObjectMetadata calls storage.v1.StorageService.GetObjectMetadata.
func (c *storageServiceClient) GetObjectMetadata(ctx context.Context, req *connect.Request[v1.GetObjectMetadataRequest]) (*connect.Response[v1.GetObjectMetadataResponse], error) {
	return c.getObjectMetadata.CallUnary(ctx, req)
}

// ListObjects calls storage.v1.StorageService.ListObjects.
func (c *storageServiceClient) ListObjects(ctx context.Context, req *connect.Request[v1.ListObjectsRequest]) (*connect.Response[v1.ListObjectsResponse], error) {
	return c.listObjects.CallUnary(ctx, req)
}

// GetDownloadURL calls storage.v1.StorageService.GetDownloadURL.
func (c *storageServiceClient) GetDownloadURL(ctx context.Context, req *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error) {
	return c.getDownloadURL.CallUnary(ctx, req)
}

// StorageServiceHandler is an implementation of the storage.v1.StorageService service.
type StorageServiceHandler interface {
	CreateBucket(context.Context, *connect.Request[v1.CreateBucketRequest]) (*connect.Response[v1.CreateBucketResponse], error)
	UploadObject(context.Context, *connect.Request[v1.UploadObjectRequest]) (*connect.Response[v1.UploadObjectResponse], error)
	GetObjectMetadata(context.Context, *connect.Request[v1.GetObjectMetadataRequest]) (*connect.Response[v1.GetObjectMetadataResponse], error)
	ListObjects(context.Context, *connect.Request[v1.ListObjectsRequest]) (*connect.Response[v1.ListObjectsResponse], error)
	GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error)
}

// NewStorageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStorageServiceHandler(svc StorageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	storageServiceMethods := v1.File_storage_v1_storage_proto.Services().ByName("StorageService").Methods()
	storageServiceCreateBucketHandler := connect.NewUnaryHandler(
		StorageServiceCreateBucketProcedure,
		svc.CreateBucket,
		connect.WithSchema(storageServiceMethods.ByName("CreateBucket")),
		connect.WithHandlerOptions(opts...),
	)
	storageServiceUploadObjectHandler := connect.NewUnaryHandler(
		StorageServiceUploadObjectProcedure,
		svc.UploadObject,
		connect.WithSchema(storageServiceMethods.ByName("UploadObject")),
		connect.WithHandlerOptions(opts...),
	)
	storageServiceGetObjectMetadataHandler := connect.NewUnaryHandler(
		StorageServiceGetObjectMetadataProcedure,
		svc.GetObjectMetadata,
		connect.WithSchema(storageServiceMethods.ByName("GetObjectMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	storageServiceListObjectsHandler := connect.NewUnaryHandler(
		StorageServiceListObjectsProcedure,
		svc.ListObjects,
		connect.WithSchema(storageServiceMethods.ByName("ListObjects")),
		connect.WithHandlerOptions(opts...),
	)
	storageServiceGetDownloadURLHandler := connect.NewUnaryHandler(
		StorageServiceGetDownloadURLProcedure,
		svc.GetDownloadURL,
		connect.WithSchema(storageServiceMethods.ByName("GetDownloadURL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/storage.v1.StorageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StorageServiceCreateBucketProcedure:
			storageServiceCreateBucketHandler.ServeHTTP(w, r)
		case StorageServiceUploadObjectProcedure:
			storageServiceUploadObjectHandler.ServeHTTP(w, r)
		case StorageServiceGetObjectMetadataProcedure:
			storageServiceGetObjectMetadataHandler.ServeHTTP(w, r)
		case StorageServiceListObjectsProcedure:
			storageServiceListObjectsHandler.ServeHTTP(w, r)
		case StorageServiceGetDownloadURLProcedure:
			storageServiceGetDownloadURLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStorageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStorageServiceHandler struct{}

func (UnimplementedStorageServiceHandler) CreateBucket(context.Context, *connect.Request[v1.CreateBucketRequest]) (*connect.Response[v1.CreateBucketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("storage.v1.StorageService.CreateBucket is not implemented"))
}

func (UnimplementedStorageServiceHandler) UploadObject(context.Context, *connect.Request[v1.UploadObjectRequest]) (*connect.Response[v1.UploadObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("storage.v1.StorageService.UploadObject is not implemented"))
}

func (UnimplementedStorageServiceHandler) GetObjectMetadata(context.Context, *connect.Request[v1.GetObjectMetadataRequest]) (*connect.Response[v1.GetObjectMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("storage.v1.StorageService.GetObjectMetadata is not implemented"))
}

func (UnimplementedStorageServiceHandler) ListObjects(context.Context, *connect.Request[v1.ListObjectsRequest]) (*connect.Response[v1.ListObjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("storage.v1.StorageService.ListObjects is not implemented"))
}

func (UnimplementedStorageServiceHandler) GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("storage.v1.StorageService.GetDownloadURL is not implemented"))
}
